package com.smartoffice.hr.model;

public class Documents {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.documents.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.documents.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.documents.document_type
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer documentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.documents.link
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.documents.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.documents.id
     *
     * @return the value of hr.documents.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.documents.id
     *
     * @param id the value for hr.documents.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.documents.user_id
     *
     * @return the value of hr.documents.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.documents.user_id
     *
     * @param userId the value for hr.documents.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.documents.document_type
     *
     * @return the value of hr.documents.document_type
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.documents.document_type
     *
     * @param documentType the value for hr.documents.document_type
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDocumentType(Integer documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.documents.link
     *
     * @return the value of hr.documents.link
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.documents.link
     *
     * @param link the value for hr.documents.link
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.documents.name
     *
     * @return the value of hr.documents.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.documents.name
     *
     * @param name the value for hr.documents.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}