package com.smartoffice.hr.model;

import java.util.Date;

public class EducationsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.major
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.degree
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.entry_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date entryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.graduate_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date graduateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.educations_user.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.id
     *
     * @return the value of hr.educations_user.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.id
     *
     * @param id the value for hr.educations_user.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.name
     *
     * @return the value of hr.educations_user.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.name
     *
     * @param name the value for hr.educations_user.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.major
     *
     * @return the value of hr.educations_user.major
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.major
     *
     * @param major the value for hr.educations_user.major
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.degree
     *
     * @return the value of hr.educations_user.degree
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.degree
     *
     * @param degree the value for hr.educations_user.degree
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.entry_date
     *
     * @return the value of hr.educations_user.entry_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.entry_date
     *
     * @param entryDate the value for hr.educations_user.entry_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.graduate_date
     *
     * @return the value of hr.educations_user.graduate_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getGraduateDate() {
        return graduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.graduate_date
     *
     * @param graduateDate the value for hr.educations_user.graduate_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setGraduateDate(Date graduateDate) {
        this.graduateDate = graduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.educations_user.user_id
     *
     * @return the value of hr.educations_user.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.educations_user.user_id
     *
     * @param userId the value for hr.educations_user.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}