package com.smartoffice.hr.model;

import java.util.Date;

public class FamilyInfos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.first_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.last_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.relation
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.job_title
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.date_of_birth
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.family_infos.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.id
     *
     * @return the value of hr.family_infos.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.id
     *
     * @param id the value for hr.family_infos.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.first_name
     *
     * @return the value of hr.family_infos.first_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.first_name
     *
     * @param firstName the value for hr.family_infos.first_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.last_name
     *
     * @return the value of hr.family_infos.last_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.last_name
     *
     * @param lastName the value for hr.family_infos.last_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.relation
     *
     * @return the value of hr.family_infos.relation
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.relation
     *
     * @param relation the value for hr.family_infos.relation
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.job_title
     *
     * @return the value of hr.family_infos.job_title
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.job_title
     *
     * @param jobTitle the value for hr.family_infos.job_title
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.date_of_birth
     *
     * @return the value of hr.family_infos.date_of_birth
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.date_of_birth
     *
     * @param dateOfBirth the value for hr.family_infos.date_of_birth
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.family_infos.user_id
     *
     * @return the value of hr.family_infos.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.family_infos.user_id
     *
     * @param userId the value for hr.family_infos.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}