package com.smartoffice.hr.model;

import java.util.Date;

public class PersonalEvaluations {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.personal_evaluations.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.personal_evaluations.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.personal_evaluations.evaluator_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer evaluatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.personal_evaluations.grade
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.personal_evaluations.date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.personal_evaluations.comments
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.personal_evaluations.id
     *
     * @return the value of hr.personal_evaluations.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.personal_evaluations.id
     *
     * @param id the value for hr.personal_evaluations.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.personal_evaluations.user_id
     *
     * @return the value of hr.personal_evaluations.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.personal_evaluations.user_id
     *
     * @param userId the value for hr.personal_evaluations.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.personal_evaluations.evaluator_id
     *
     * @return the value of hr.personal_evaluations.evaluator_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getEvaluatorId() {
        return evaluatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.personal_evaluations.evaluator_id
     *
     * @param evaluatorId the value for hr.personal_evaluations.evaluator_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setEvaluatorId(Integer evaluatorId) {
        this.evaluatorId = evaluatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.personal_evaluations.grade
     *
     * @return the value of hr.personal_evaluations.grade
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.personal_evaluations.grade
     *
     * @param grade the value for hr.personal_evaluations.grade
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.personal_evaluations.date
     *
     * @return the value of hr.personal_evaluations.date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.personal_evaluations.date
     *
     * @param date the value for hr.personal_evaluations.date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.personal_evaluations.comments
     *
     * @return the value of hr.personal_evaluations.comments
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.personal_evaluations.comments
     *
     * @param comments the value for hr.personal_evaluations.comments
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}