package com.smartoffice.hr.model;

import java.util.Date;

public class SalaryHistories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.salary_gross
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer salaryGross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.pit
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Double pit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.inps
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Double inps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.pf
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Double pf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.currency_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer currencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.salary_histories.salary_net
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer salaryNet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.id
     *
     * @return the value of hr.salary_histories.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.id
     *
     * @param id the value for hr.salary_histories.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.user_id
     *
     * @return the value of hr.salary_histories.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.user_id
     *
     * @param userId the value for hr.salary_histories.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.salary_gross
     *
     * @return the value of hr.salary_histories.salary_gross
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getSalaryGross() {
        return salaryGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.salary_gross
     *
     * @param salaryGross the value for hr.salary_histories.salary_gross
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setSalaryGross(Integer salaryGross) {
        this.salaryGross = salaryGross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.pit
     *
     * @return the value of hr.salary_histories.pit
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Double getPit() {
        return pit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.pit
     *
     * @param pit the value for hr.salary_histories.pit
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPit(Double pit) {
        this.pit = pit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.inps
     *
     * @return the value of hr.salary_histories.inps
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Double getInps() {
        return inps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.inps
     *
     * @param inps the value for hr.salary_histories.inps
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setInps(Double inps) {
        this.inps = inps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.pf
     *
     * @return the value of hr.salary_histories.pf
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Double getPf() {
        return pf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.pf
     *
     * @param pf the value for hr.salary_histories.pf
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPf(Double pf) {
        this.pf = pf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.currency_id
     *
     * @return the value of hr.salary_histories.currency_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.currency_id
     *
     * @param currencyId the value for hr.salary_histories.currency_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.date
     *
     * @return the value of hr.salary_histories.date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.date
     *
     * @param date the value for hr.salary_histories.date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.salary_histories.salary_net
     *
     * @return the value of hr.salary_histories.salary_net
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getSalaryNet() {
        return salaryNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.salary_histories.salary_net
     *
     * @param salaryNet the value for hr.salary_histories.salary_net
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setSalaryNet(Integer salaryNet) {
        this.salaryNet = salaryNet;
    }
}