package com.smartoffice.hr.model;

import java.util.Date;

public class Trainings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.organization
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String organization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.date_from
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date dateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.date_to
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date dateTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.number_of_hours
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer numberOfHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.trainings.mark
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.id
     *
     * @return the value of hr.trainings.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.id
     *
     * @param id the value for hr.trainings.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.name
     *
     * @return the value of hr.trainings.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.name
     *
     * @param name the value for hr.trainings.name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.organization
     *
     * @return the value of hr.trainings.organization
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.organization
     *
     * @param organization the value for hr.trainings.organization
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.user_id
     *
     * @return the value of hr.trainings.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.user_id
     *
     * @param userId the value for hr.trainings.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.date_from
     *
     * @return the value of hr.trainings.date_from
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.date_from
     *
     * @param dateFrom the value for hr.trainings.date_from
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.date_to
     *
     * @return the value of hr.trainings.date_to
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDateTo() {
        return dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.date_to
     *
     * @param dateTo the value for hr.trainings.date_to
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.number_of_hours
     *
     * @return the value of hr.trainings.number_of_hours
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getNumberOfHours() {
        return numberOfHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.number_of_hours
     *
     * @param numberOfHours the value for hr.trainings.number_of_hours
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setNumberOfHours(Integer numberOfHours) {
        this.numberOfHours = numberOfHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.trainings.mark
     *
     * @return the value of hr.trainings.mark
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.trainings.mark
     *
     * @param mark the value for hr.trainings.mark
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}