package com.smartoffice.hr.model;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.username
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.phone_mobile
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String phoneMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.phone_home
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String phoneHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.email_company
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String emailCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.email_personal
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String emailPersonal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.date_of_birth
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.status_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.password_hash
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.hiring_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date hiringDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.chief_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer chiefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.political
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Boolean political;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.passport
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String passport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.enabled
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.role_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.first_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.last_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.fathers_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String fathersName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.address
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.users.birth_place
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private String birthPlace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.id
     *
     * @return the value of hr.users.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.id
     *
     * @param id the value for hr.users.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.username
     *
     * @return the value of hr.users.username
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.username
     *
     * @param username the value for hr.users.username
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.phone_mobile
     *
     * @return the value of hr.users.phone_mobile
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getPhoneMobile() {
        return phoneMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.phone_mobile
     *
     * @param phoneMobile the value for hr.users.phone_mobile
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPhoneMobile(String phoneMobile) {
        this.phoneMobile = phoneMobile == null ? null : phoneMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.phone_home
     *
     * @return the value of hr.users.phone_home
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getPhoneHome() {
        return phoneHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.phone_home
     *
     * @param phoneHome the value for hr.users.phone_home
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPhoneHome(String phoneHome) {
        this.phoneHome = phoneHome == null ? null : phoneHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.email_company
     *
     * @return the value of hr.users.email_company
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getEmailCompany() {
        return emailCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.email_company
     *
     * @param emailCompany the value for hr.users.email_company
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setEmailCompany(String emailCompany) {
        this.emailCompany = emailCompany == null ? null : emailCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.email_personal
     *
     * @return the value of hr.users.email_personal
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getEmailPersonal() {
        return emailPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.email_personal
     *
     * @param emailPersonal the value for hr.users.email_personal
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setEmailPersonal(String emailPersonal) {
        this.emailPersonal = emailPersonal == null ? null : emailPersonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.date_of_birth
     *
     * @return the value of hr.users.date_of_birth
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.date_of_birth
     *
     * @param dateOfBirth the value for hr.users.date_of_birth
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.status_id
     *
     * @return the value of hr.users.status_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.status_id
     *
     * @param statusId the value for hr.users.status_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.password_hash
     *
     * @return the value of hr.users.password_hash
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.password_hash
     *
     * @param passwordHash the value for hr.users.password_hash
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash == null ? null : passwordHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.hiring_date
     *
     * @return the value of hr.users.hiring_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getHiringDate() {
        return hiringDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.hiring_date
     *
     * @param hiringDate the value for hr.users.hiring_date
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setHiringDate(Date hiringDate) {
        this.hiringDate = hiringDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.chief_id
     *
     * @return the value of hr.users.chief_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getChiefId() {
        return chiefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.chief_id
     *
     * @param chiefId the value for hr.users.chief_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setChiefId(Integer chiefId) {
        this.chiefId = chiefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.political
     *
     * @return the value of hr.users.political
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Boolean getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.political
     *
     * @param political the value for hr.users.political
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPolitical(Boolean political) {
        this.political = political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.passport
     *
     * @return the value of hr.users.passport
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getPassport() {
        return passport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.passport
     *
     * @param passport the value for hr.users.passport
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setPassport(String passport) {
        this.passport = passport == null ? null : passport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.enabled
     *
     * @return the value of hr.users.enabled
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.enabled
     *
     * @param enabled the value for hr.users.enabled
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.role_id
     *
     * @return the value of hr.users.role_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.role_id
     *
     * @param roleId the value for hr.users.role_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.first_name
     *
     * @return the value of hr.users.first_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.first_name
     *
     * @param firstName the value for hr.users.first_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.last_name
     *
     * @return the value of hr.users.last_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.last_name
     *
     * @param lastName the value for hr.users.last_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.fathers_name
     *
     * @return the value of hr.users.fathers_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getFathersName() {
        return fathersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.fathers_name
     *
     * @param fathersName the value for hr.users.fathers_name
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setFathersName(String fathersName) {
        this.fathersName = fathersName == null ? null : fathersName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.address
     *
     * @return the value of hr.users.address
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.address
     *
     * @param address the value for hr.users.address
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.users.birth_place
     *
     * @return the value of hr.users.birth_place
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.users.birth_place
     *
     * @param birthPlace the value for hr.users.birth_place
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace == null ? null : birthPlace.trim();
    }


    @Override
    public String toString() {
        return "Users{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", phoneMobile='" + phoneMobile + '\'' +
                ", phoneHome='" + phoneHome + '\'' +
                ", emailCompany='" + emailCompany + '\'' +
                ", emailPersonal='" + emailPersonal + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", statusId=" + statusId +
                ", passwordHash='" + passwordHash + '\'' +
                ", hiringDate=" + hiringDate +
                ", chiefId=" + chiefId +
                ", political=" + political +
                ", passport='" + passport + '\'' +
                ", enabled=" + enabled +
                ", roleId=" + roleId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", fathersName='" + fathersName + '\'' +
                ", address='" + address + '\'' +
                ", birthPlace='" + birthPlace + '\'' +
                '}';
    }
}