package com.smartoffice.hr.model;

import java.util.Date;

public class UserInPosts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.date_from
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date dateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.date_end
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Date dateEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.job_title_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer jobTitleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.department_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.external_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer externalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.user_in_posts.contract_type
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    private Integer contractType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.id
     *
     * @return the value of hr.user_in_posts.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.id
     *
     * @param id the value for hr.user_in_posts.id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.user_id
     *
     * @return the value of hr.user_in_posts.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.user_id
     *
     * @param userId the value for hr.user_in_posts.user_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.date_from
     *
     * @return the value of hr.user_in_posts.date_from
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.date_from
     *
     * @param dateFrom the value for hr.user_in_posts.date_from
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.date_end
     *
     * @return the value of hr.user_in_posts.date_end
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.date_end
     *
     * @param dateEnd the value for hr.user_in_posts.date_end
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.job_title_id
     *
     * @return the value of hr.user_in_posts.job_title_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getJobTitleId() {
        return jobTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.job_title_id
     *
     * @param jobTitleId the value for hr.user_in_posts.job_title_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setJobTitleId(Integer jobTitleId) {
        this.jobTitleId = jobTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.department_id
     *
     * @return the value of hr.user_in_posts.department_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.department_id
     *
     * @param departmentId the value for hr.user_in_posts.department_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.external_id
     *
     * @return the value of hr.user_in_posts.external_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.external_id
     *
     * @param externalId the value for hr.user_in_posts.external_id
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setExternalId(Integer externalId) {
        this.externalId = externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.user_in_posts.contract_type
     *
     * @return the value of hr.user_in_posts.contract_type
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public Integer getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.user_in_posts.contract_type
     *
     * @param contractType the value for hr.user_in_posts.contract_type
     *
     * @mbg.generated Fri May 05 11:45:26 UZT 2017
     */
    public void setContractType(Integer contractType) {
        this.contractType = contractType;
    }
}